### ISSUE TITLE
Set Up UI kit

### ISSUE THREAD

**Issue by DylanNeil** [DylanNeil/moviereviews#2]
#### Description
I need to use a UI kit.

#### Tasks

- [ ] See if any uikits have some sort of figma or xd configuration
- [ ] install UI kit in project
- [ ] Install UI kit in design
