### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by DylanNeil** [DylanNeil/moviereviews#8]
#### Description
Using the wireframe that was created, build a mockup of this project with the correct color scheme, shadowing, etc..

#### Files
moviereviews file, in the design folder

#### Tasks

- [ ] Componentize from wireframe (make sure all is reusable)
- [ ] Document changes and progress
- [ ] Make sure all transitions are working properly
